//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fancy_Magazine.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feature_Boxes
    {
        public int feature_boxes_id { get; set; }
        public string feature_boxes_title { get; set; }
        public string feature_boxes_icon { get; set; }
        public string feature_boxes_content { get; set; }
        public string feature_boxes_url { get; set; }
    }
}
