//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fancy_Magazine.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Industry
    {
        public int industries_id { get; set; }
        public string industries_title { get; set; }
        public string industries_content { get; set; }
        public string industries_img { get; set; }
        public string industries_url { get; set; }
    }
}
