//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fancy_Magazine.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project_Area
    {
        public int project_area_id { get; set; }
        public string project_area_title { get; set; }
        public string project_area_content { get; set; }
        public string project_area_url { get; set; }
    }
}
