//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fancy_Magazine.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service_Area_Contents
    {
        public int service_contents_id { get; set; }
        public string service_contents_title { get; set; }
        public string service_contents_content { get; set; }
        public string service_contents_icon { get; set; }
    }
}
