//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fancy_Magazine.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Slider
    {
        public int slider_id { get; set; }
        public string slider_title { get; set; }
        public string slider_img { get; set; }
        public string slider_first_url { get; set; }
        public string slider_second_url { get; set; }
    }
}
